# Generated by Django 3.2.9 on 2021-11-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=200, verbose_name='User Name')),
                ('user_Email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('user_designation', models.CharField(max_length=100, verbose_name='User Designation')),
                ('user_password', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
    ]
