# Generated by Django 3.2.9 on 2021-11-08 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
