# Generated by Django 3.2.9 on 2021-11-08 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0002_users_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='User registration date'),
        ),
    ]
