# Generated by Django 3.2.9 on 2021-11-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0003_alter_users_date_of_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
