# Generated by Django 3.2.9 on 2021-11-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0005_alter_user_date_of_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_and_grades_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Grade')),
                ('fees', models.IntegerField(verbose_name='Fees')),
                ('no_of_student', models.IntegerField(verbose_name='Total no of student in Class')),
                ('collect_amount', models.IntegerField()),
            ],
        ),
    ]
