# Generated by Django 3.2.9 on 2021-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0006_fees_and_grades_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('mid_name', models.CharField(blank=True, max_length=100, verbose_name='Mid Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=200, verbose_name='Father Name')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Admin_registration',
        ),
    ]
