# Generated by Django 3.2.9 on 2021-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0007_auto_20211110_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='address',
            field=models.TextField(default=' ', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='email',
            field=models.EmailField(default=' ', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='father_cnic_no',
            field=models.CharField(default=' ', max_length=15, verbose_name='Father CNIC no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='father_contact_no',
            field=models.CharField(default='', max_length=12, verbose_name='Father Contact no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='home_phone_no',
            field=models.CharField(default='', max_length=15, verbose_name='Home Phone No'),
            preserve_default=False,
        ),
    ]
