# Generated by Django 3.2.9 on 2021-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0008_auto_20211110_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='home_phone_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Home Phone No'),
        ),
    ]
