# Generated by Django 3.2.9 on 2021-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0009_alter_student_registration_home_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='home_phone_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Home Phone No'),
        ),
    ]
