# Generated by Django 3.2.9 on 2021-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0010_alter_student_registration_home_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='image',
            field=models.ImageField(default='media/images/profile_pic.png', upload_to=''),
        ),
    ]
