# Generated by Django 3.2.9 on 2021-11-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0013_alter_student_registration_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='grade',
        ),
    ]
