# Generated by Django 3.2.9 on 2021-11-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0017_student_registration_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='gender',
            field=models.CharField(default='', max_length=6, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
