# Generated by Django 3.2.9 on 2021-11-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0018_student_registration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='image',
            field=models.ImageField(default='media/images/profile_pic.png', upload_to='media/images/'),
        ),
    ]
