# Generated by Django 3.2.9 on 2021-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0020_alter_student_registration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student_registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student_registration',
            name='mid_name',
        ),
        migrations.AddField(
            model_name='student_registration',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
