# Generated by Django 3.2.9 on 2021-11-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0021_auto_20211111_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_and_grades_details',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total no of student in class'),
            preserve_default=False,
        ),
    ]
