# Generated by Django 3.2.9 on 2021-11-11 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feesdata', '0022_fees_and_grades_details_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='November', max_length=20, verbose_name='Month')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='User registration date')),
                ('collected_by', models.CharField(max_length=200, verbose_name='Collector Name')),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feesdata.student_registration')),
            ],
        ),
    ]
